TESTS = test_package_manager.ex 
INTERPRETER = eui

all: test_package_manager
test_package_manager: test_random_test
	${INTERPRETER} test_package_manager.ex
test_random_test:
	${INTERPRETER} test_package_manager.ex

